"""
Routing with LangGraph

Customer Support System: Using the routing workflow, build a customer support workflow that has different categories.

Categories:
- Billing
- Technical Support
- Refund Request
- General Inquiry

Graph:
START -> Classification Agent -> Conditional Routing based on "route_to_agent" function -> Agent Node (Billing/Technical/Refund/General) -> END

1. First Classification agent is called to classify the customer query. 
    It would determine whether the customer query is of type "billing", "technical", "refund", or "general".
    It then stores the classification in the query_category field of the state.
    Also, it stores the "confidence" and "reasoning" for the classification in the QueryClassification object.

2. Based on the classification, a route_to_agent function will determine which agent would serve the purpose.

3. Graph would invoke the appropriate agent node based on the classification.
"""

from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END
from typing import TypedDict, Literal
from pydantic import BaseModel, Field
from dotenv import load_dotenv

load_dotenv()


# Define state schema
class SupportState(TypedDict):
    customer_query: str
    query_category: str
    response: str # output generated by any agent node
    tools_used: list[str] # tools used by any agent node


# Initialize LLM
llm = ChatOpenAI(model="gpt-4o-mini")


# Define structured schema for query classification details only
class QueryClassification(BaseModel):
    category: Literal["billing", "technical", "refund", "general"]
    confidence: float = Field(description="Confidence score between 0 and 1", ge=0.0, le=1.0)
    reasoning: str = Field(description="Brief explanation of why this classification was chosen")


# Create node - Classification agent to classify the customer query
def classify_query(state: SupportState) -> SupportState:
    print("\n ROUTER: Classifying customer query...")
    
    # Create classifier LLM with structured output
    classifier_llm = llm.with_structured_output(QueryClassification)

    prompt = f"""Classify the following customer support query into one of these categories:
    - billing: Questions about invoices, payments, charges, pricing
    - technical: Technical issues, bugs, errors, functionality problems, integration issues
    - refund: Refund requests, returns, cancellations, chargebacks, payment disputes
    - general: General questions, feature inquiries, policy inquiries, account information, information requests
    
    Customer Query: {state['customer_query']}
    
    Classify accurately based on the primary intent. 
    Return the classification with confidence score and reasoning.
    """
    
    # Invoke classifier with prompt
    classification = classifier_llm.invoke(prompt)
    
    # Update state
    category = classification.category
    confidence = classification.confidence
    reasoning = classification.reasoning
    
    """
        Note: Here you can use Command() API to route to specific agent based on the category determined above
        But we use simple conditional routing in our workflow
    """

    print(f"======= Router: Classified as '{category}' with confidence {confidence:.2f} and reasoning: {reasoning} =======")

    return {
        "query_category": category # Return the state category
    }
    

# Create node Billing Agent - Based on the "billing" classifcation of user query, handle billing queries
def handle_billing(state: SupportState) -> SupportState:
    print("\n BILLING AGENT: Processing billing query...")

    billing_prompt = f"""You are a billing specialist. Handle the following customer billing query:
    
    {state['customer_query']}
    
    Provide a helpful response that:
    - References billing policies and procedures
    - Offers to check their account details
    - Provides clear next steps
    - Mentions relevant payment options

    Keep it professional and reassuring.
    """
    
    response = llm.invoke(billing_prompt)
    
    print(f"========= Billing Agent Response Generated =========")
    
    return {
        "response": response.content,
        "tools_used": ["billing_api", "billing_database", "payment_processor"]
    }


# Create node Technical Agent - Based on the "technical" classifcation of user query, handle technical queries
def handle_technical(state: SupportState) -> SupportState:
    print("\n TECHNICAL AGENT: Processing technical query...")

    technical_prompt = f"""You are a technical support specialist. Handle the following customer technical query:
    
    {state['customer_query']}
    
    Provide a helpful response that:
    - References technical documentation and offers troubleshooting steps
    - Offers to check their system logs
    - Ask clearifying questions if needed
    - Provides workarounds if applicable

    Be clear, technical but accessible.
    """
    
    response = llm.invoke(technical_prompt)
    
    print(f"========= Technical Agent Response Generated =========")

    return {
        "response": response.content,
        "tools_used": ["knowledge_base", "system_logs", "bug_tracker"]
    }


# Create node Refund Agent - Based on the "refund" classifcation of user query, handle refund queries
def handle_refund(state: SupportState) -> SupportState:
    print("\n REFUND AGENT: Processing refund query...")

    refund_prompt = f"""You are a refund specialist. Handle the following customer refund query:
    
    {state['customer_query']}
    
    Provide a helpful response that:
    - Explains the refund policy clearly
    - Outlines the refund process and timeline
    - Asks for necessary information (order number, reason, etc.)
    - Mentions relevant refund options
    - Shows empathy and understanding

    Be empathetic, clear, concise, and helpful.
    """
    
    response = llm.invoke(refund_prompt)
    
    print(f"========= Refund Agent Response Generated =========")
    
    return {
        "response": response.content,
        "tools_used": ["order_database", "refund_processor"]
    }


# Create node General Agent - Based on the "general" classifcation of user query, handle general queries
def handle_general(state: SupportState) -> SupportState:
    print("\n GENERAL AGENT: Processing general query...")

    general_prompt = f"""You are a general support specialist. Handle the following customer general query:
    
    {state['customer_query']}
    
    Provide a helpful response that:
    - Answers the customer's question clearly
    - Offers additional assistance if needed
    - Provides relevant information about the company, products, or services
    - Suggests related features they might find useful

    Be friendly and informative.
    """
    
    response = llm.invoke(general_prompt)
    
    print(f"========= General Agent Response Generated =========")
    
    return {
        "response": response.content,
        "tools_used": ["knowledge_base", "company_info", "faq_database"]
    }


# Create function to route to appropriate agent
def route_to_agent(state: SupportState) -> Literal["billing_agent", "technical_agent", "refund_agent", "general_agent"]:
    print(f"\n ROUTING: Directing to: {state['query_category']} agent\n")

    category = state["query_category"]
    if category == "billing":
        return "billing_agent"
    elif category == "technical":
        return "technical_agent"
    elif category == "refund":
        return "refund_agent"
    else:
        return "general_agent"


# Create the graph
graph = StateGraph(SupportState)

# Add nodes
graph.add_node("classifier", classify_query)
graph.add_node("billing_handler_agent", handle_billing)
graph.add_node("technical_handler_agent", handle_technical)
graph.add_node("refund_handler_agent", handle_refund)
graph.add_node("general_handler_agent", handle_general)

graph.set_entry_point("classifier") # OR you can do: graph.add_edge(START, "classifier")

graph.add_conditional_edges(
    "classifier",
    route_to_agent,  # After classifer, use route_to_agent function to determine which agent to route to
    {
        "billing_agent": "billing_handler_agent",
        "technical_agent": "technical_handler_agent",
        "refund_agent": "refund_handler_agent",
        "general_agent": "general_handler_agent"
    }
)

graph.add_edge("billing_handler_agent", END)
graph.add_edge("technical_handler_agent", END)
graph.add_edge("refund_handler_agent", END)
graph.add_edge("general_handler_agent", END)

app = graph.compile()

# Now, let's test the routing using multiple user query prompts

# 1. Billing query
billing_query = "I was charged twice for my subscription this month. Can you please help me?"

# 2. Technical query
technical_query = "The app keeps crashing when I try to upload files larger than 10 MB size."

# 3. Refund query
refund_query = "I'd like to request a refund for my recent purchase. It doesn't meet my expectations."

# 4. General query
general_query = "What additional features do you offer as part of a Pro plan?"

# Test the routing
print("Testing routing with multiple queries...\n")

for i, query in enumerate([billing_query, technical_query, refund_query, general_query], 1):
    print(f"\n{'='*60}")
    print(f"TEST {i}: {query}")
    print(f"{'='*60}")
    
    result = app.invoke({"customer_query": query}) # Pass the user query to the graph
    
    print(f"\nResponse: {result['response']}")
    print(f"Tools Used: {result['tools_used']}")
    print(f"Category: {result['query_category']}")
    print(f"{'='*60}\n")

