"""
=====================================================================
Orchestrator and Worker Pattern Example: Uses Dynamic Graphs
=====================================================================

How it works:
1. Start to Orchestrator: 
    - The process begins at the START and immediately moves to the Orchestrator (plan_research)

2. Dynamic Fan-out: 
    - The add_conditional_edges call using create_conditional_workers is the most important part. 
    - It looks at the subtasks created by the Orchestrator and uses the Send() API to trigger multiple worker (research_worker) nodes in parallel.

3. Fan-in to Synthesis: 
    - Once every parallel worker node has finished its task, the flow "fans in" to the synthesizer.

4. Completion: 
    - After the report is synthesized, the workflow reaches the END
=====================================================================
POC: Research Project Report Generator

Orchestrator: 
    - Breaks down the research project into smaller tasks
    - Assigns tasks to workers
    - Coordinates the work

Worker: 
    - Performs the assigned tasks
    - Returns the results to the orchestrator

Synthesizer:
    - Combines the results from all workers into a final report

Real Life Examples:
    - Research Project Report Generator
    - Test suite execution. Each worker runs a specific test case. Finally, the orchestrator compiles the results.
"""


from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END
from langgraph.types import Send
from typing import TypedDict, List, Annotated
from operator import add
from pydantic import BaseModel, Field
from dotenv import load_dotenv

load_dotenv()

# Overall state for the orchestrator
class OverallState(TypedDict):
    # Research topic
    research_topic: str

    # Breakdown of the topic into subtopics
    sub_topics: List[str]
    
    # Each Worker node investigates one subtopic and adds its findings to this list.
    # "add" function is the Reducer that appends the findings to the list
    # dict structure: {worker_id: int, subtopic: str, research_result: str}
    # Worder node would create this dictionary structure and add it to the list
    worker_findings: Annotated[list[dict], add] # dict structure: {worker_id: int, subtopic: str, research_result: str}

    # Final report generated by the orchestrator
    final_report: str


# State for each worker
class WorkerState(TypedDict):
    # Worker ID
    worker_id: int

    # Research Topic
    research_topic: str # Mapped from parent's (OverallState) research_topic

    # Subtopic to research by this worker
    subtopic: str



# Orchestrator Output
class ResearchPlan(BaseModel):
    # List of subtopics to research
    sub_topics: List[str] = Field(description="List of subtopics to research", max_length=5)

    # Brief explanation of why these sub-topics were chosen
    reasoning: str = Field(description="Brief explanation of why these sub-topics were chosen")


llm = ChatOpenAI(model="gpt-4o-mini")


# Orechestrator Node to plan the research by dividing the topic into subtopics
def plan_research(overall_state: OverallState) -> OverallState:
    print(f"=" * 70)
    print(f"Orchestrator: Planning research strategy for '{overall_state['research_topic']}'\n")
    print(f"=" * 70)

    planner_llm = llm.with_structured_output(ResearchPlan)
    
    planner_prompt = f"""
        You are a research strategist planning a compmprehensive investigation.

        Research Topic: {overall_state['research_topic']}
        
        Critical Instruction: Generate a list of 3-5 subtopics that will help investigate the research topic comprehensively.

        Each subtopic should be:
        - Specific and focused on a distinct aspect of the research topic
        - Relevant to the overall topic
        - Complementary to the other subtopics
        - Concrete enough to guide targeted research

        Examples of good subtopics:
        - "Clinical trial results and efficacy data"
        - "Economic impact and cost-benefit analysis"
        - "Regulatory framework and compliance requirements"
        - "Patient outcomes and quality of life metrics"
        - "Industry adoption rates and market trends"

        Generate sources that will provide comprehensive coverage of each subtopic.
        """

    research_plan = planner_llm.invoke(planner_prompt)
    
    print(f"📚Orchestrator generated {len(research_plan.sub_topics)} subtopics")
    print(f"Reasoning: {research_plan.reasoning}")

    # Add the subtopics to the state
    overall_state["sub_topics"] = research_plan.sub_topics

    return overall_state



# Worker Node
def research_worker(worker_state: WorkerState) -> OverallState:
    worker_id = worker_state["worker_id"]
    research_topic = worker_state["research_topic"]
    subtopic = worker_state["subtopic"]
    
    print(f"🔎 Worker {worker_id}: Researching '{subtopic}'\n")
    print(f"=" * 40)

    worker_subtopic_research_prompt = f"""
        You are a specialized research agent investigating: {research_topic}

        Your specific focus area: {subtopic}
        
        Conduct thorough research on this focus area and provide:
        1. Key findings and insights (3-5 specific points)
        - What are the most important discoveries or facts?

        2. Data & Statistics
        - Relevant numbers, percentages, or quantitative information

        3. Insights & Analysis
        - What does this information mean?
        - How does it relate to the broader topic?

        4. Sources & Credibility
        - Types of sources you would consult (academic, industry, government, etc.)
        - How to evaluate source reliability

        5. Implications
        - Why does this matter for understanding the overall topic?

        Be specific, factual, and provide depth on this particular aspect.
        """
    
    worker_subtopic_research_result = llm.invoke(worker_subtopic_research_prompt)
    
    #print(f"Worker {worker_id} completed research for '{subtopic}'")
    #print(f"Result: {worker_subtopic_research_result}")
    
    # Add the research result with worker details to the state
    findings = {
        "worker_id": worker_id,
        "subtopic": subtopic,
        "research_result": worker_subtopic_research_result
    }
    
    print(f"✅ Worker {worker_id}: Research completed.")

    # Add this worker findings to the overall state and return it
    return {
        "worker_findings" : [findings]
    }
    


# Synthesizer Node
def synthesizer(overall_state: OverallState) -> OverallState:
    print(f"=" * 70)
    print(f"Synthesizer: Compiling final report from {len(overall_state['worker_findings'])} worker findings\n")
    print(f"=" * 70)

    all_findings = f"\n\n".join([
        f"RESEARCH AREA BY {one_finding['worker_id']}: {one_finding['subtopic']}\n{one_finding['research_result']}" 
        for one_finding in overall_state['worker_findings']
    ])
    
    prompt = f"""
        You are a synthesizer agent compiling a comprehensive research report on: {overall_state["research_topic"]}
        
        You have received detailed findings from {len(overall_state['worker_findings'])} specialized researchers, 
        each investigating a different aspect of this topic.

        RESEARCH FINDINGS:
        {all_findings}

        Create a cohesive, well-structured research report (200-500 words) with the following sections:
        1. EXECUTIVE SUMMARY: 
        - Provide a high-level overview of the key insights and main findings
        
        2. INTRODUCTION: 
        - Set the context and scope of the research
        
        3. KEY FINDINGS: 
        - Integrate insights from all research areas
        - Organize thematically rather than by source
        - Use specific data and examples
        
        4. ANALYSIS & SYNTHESIS: 
        - Identify patterns, connections, and contradictions across findings
        - Highlight connections and relationships
        - Note any contradictions or tensions
        
        5. IMPLICATIONS: 
        - What do these findings mean?
        - Who is affected and how?
        
        6. CONCLUSION: 
        - Main takeaways and key insights
        - Areas of further research

        IMPORTANT:
        - Write this as a unified, flowing report, NOT as separate sections from each researcher
        - Integrate findings naturally across themes
        - Use specific examples and data from the research
        - Make it professional and authoritative
        """
    
    final_report = llm.invoke(prompt)
    
    print(f"✔️ Synthesizer: Final report compiled")


    return {
        "final_report": final_report
    }




# Conditional edge function to dynamically create workers and dispatch them
def create_conditional_workers(state: OverallState) -> str:
    print(f"Creating conditional workers for {len(state['sub_topics'])} subtopics, and dispatching dynamically.")

    # For each subtopic from the OverallState, build a Worker node state, add it to a list, and send that list for execution
    return [
    Send("research_worker", {
        "subtopic": one_subtopic,
        "worker_id": i + 1,
        "research_topic": state["research_topic"] # set the research topic from the OverallState object
    })
    for i, one_subtopic in enumerate(state["sub_topics"]) # For each subtopic in the OverallState object, create a WorkerNode State and send it.
   ]




# Main Workflow
def main():
    print("Starting Multi-Agent Research Workflow with Worker Pattern")
    print("=" * 70)
    
    # Initialize the workflow
    workflow = StateGraph(OverallState)
    
    # Add nodes
    workflow.add_node("orchestrator", plan_research)
    workflow.add_node("research_worker", research_worker)
    workflow.add_node("synthesizer", synthesizer)
    
    # Define edges
    workflow.add_edge(START, "orchestrator")

    workflow.add_conditional_edges("orchestrator", create_conditional_workers, ["research_worker"])
    
    workflow.add_edge("research_worker", "synthesizer")
    workflow.add_edge("synthesizer", END)
    
    # Compile the workflow
    graph = workflow.compile()
    
    # Run the workflow
    print("\nStarting workflow execution...\n")
    
    initial_state = {
        "research_topic": "The Impact of AI on Healthcare",
        "subtopics": [],
        "worker_findings": [],
        "final_report": ""
    }
    
    result = graph.invoke(initial_state)
    
    print("\n" + "=" * 70)
    print("WORKFLOW COMPLETED")
    print("=" * 70)
    print(f"\nFinal Report:")
    print(result["final_report"].content)
    
    return result

if __name__ == "__main__":
    main()