"""HR Policy Service — initialises the vector store and answers policy questions."""

import logging
import os
from functools import lru_cache
from typing import Optional

from app.services.vector_store import VectorStoreService
from app.services.ai_service import AIService

logger = logging.getLogger(__name__)

_vector_store: Optional[VectorStoreService] = None
_ai_service: Optional[AIService] = None


def _get_services() -> tuple[VectorStoreService, AIService]:
    """Lazily initialise and return the VectorStoreService and AIService singletons.

    Returns:
        A tuple of (VectorStoreService, AIService).
    """
    global _vector_store, _ai_service

    if _vector_store is None or _ai_service is None:
        openai_api_key = os.environ.get("OPENAI_API_KEY", "")
        chroma_dir = os.environ.get("CHROMA_PERSIST_DIR", "./chroma_data")
        hr_pdf_path = os.environ.get("HR_POLICIES_PATH", "../hr_policies/hr_policies.pdf")

        _vector_store = VectorStoreService(
            persist_directory=chroma_dir,
            openai_api_key=openai_api_key,
        )

        # Load HR policies PDF into ChromaDB if not already loaded
        if os.path.exists(hr_pdf_path):
            try:
                inserted = _vector_store.load_pdf(hr_pdf_path, source_label="hr_policies")
                if inserted:
                    logger.info("Loaded %d chunks from HR policies PDF.", inserted)
            except Exception as exc:
                logger.error("Failed to load HR policies PDF: %s", exc)
        else:
            logger.warning("HR policies PDF not found at path: %s", hr_pdf_path)

        _ai_service = AIService(
            openai_api_key=openai_api_key,
            vector_store=_vector_store,
        )

    return _vector_store, _ai_service


def answer_hr_policy_question(question: str, employee_context: Optional[str] = None) -> str:
    """Answer a question using the HR policy vector store and GPT-4.

    Ensures the vector store is initialised and the HR policies PDF is loaded
    before generating a response.

    Args:
        question: The question to answer.
        employee_context: Optional string with information about the requesting employee.

    Returns:
        Answer string generated by the AI service.
    """
    _, ai_service = _get_services()
    return ai_service.generate_response(question, employee_context=employee_context)


def get_ai_service() -> AIService:
    """Return the initialised AIService singleton.

    Returns:
        AIService instance ready for use.
    """
    _, ai_service = _get_services()
    return ai_service


def get_vector_store() -> VectorStoreService:
    """Return the initialised VectorStoreService singleton.

    Returns:
        VectorStoreService instance ready for use.
    """
    vector_store, _ = _get_services()
    return vector_store
